// VERIFICATION ERROR
const ERR_NO_TOKEN = "ERR_NO_TOKEN"
const ERR_INVALID_TOKEN = "ERR_INVALID_TOKEN"
const ERR_UNAUTHORISED_USER = "ERR_UNAUTHORISED_USER"
const ERR_UNAUTHORISED_ADMIN = "ERR_UNAUTHORISED_ADMIN"
const ERR_UNAUTHORISED_INSTRUCTOR = "ERR_UNAUTHORISED_INSTRUCTOR"
const ERR_UNAUTHORISED_STUDENT = "ERR_UNAUTHORISED_STUDENT"


// ERROR MESSAGES
const ERR_INSUFFICIENT_REQ = "ERR_INSUFFICIENT_REQ"
const ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS"
const ERR_INVALID_USER_ID = "ERR_INVALID_USER_ID"
const ERR_INVALID_USER_TYPE = "ERR_INVALID_USER_TYPE"
const ERR_USER_ALREADY_DELETED = "ERR_USER_ALREADY_DELETED"
const ERR_USER_ALREADY_EXISTS = "ERR_USER_ALREADY_EXISTS"
const ERR_USER_NOT_FOUND = "ERR_USER_DOES_NOT_EXISTS"
const ERR_USERS_NOT_FOUND = "ERR_USERS_NOT_FOUND"

// STATUS CODES
const STATUS_SUCCESS_OK = 200
const STATUS_SUCCESS_CREATED = 201
const STATUS_ERR_CLIENT_BAD_REQUEST = 400
const STATUS_ERR_CLIENT_UNAUTHORISED = 401
const STATUS_ERR_CLIENT_FORBIDDEN = 403
const STATUS_ERR_CLIENT_NOT_FOUND = 404


module.exports = {
    ERR_INSUFFICIENT_REQ,
    ERR_INVALID_USER_TYPE,
    ERR_USER_ALREADY_EXISTS,
    ERR_INVALID_CREDENTIALS,
    ERR_NO_TOKEN,
    ERR_INVALID_TOKEN,
    ERR_UNAUTHORISED_USER,
    ERR_UNAUTHORISED_ADMIN,
    ERR_UNAUTHORISED_INSTRUCTOR,
    ERR_UNAUTHORISED_STUDENT,
    STATUS_SUCCESS_OK,
    STATUS_SUCCESS_CREATED,
    STATUS_ERR_CLIENT_BAD_REQUEST,
    STATUS_ERR_CLIENT_UNAUTHORISED,
    STATUS_ERR_CLIENT_FORBIDDEN,
    STATUS_ERR_CLIENT_NOT_FOUND,
    ERR_INVALID_USER_ID,
    ERR_USER_ALREADY_DELETED,
    ERR_USER_NOT_FOUND,
    ERR_USERS_NOT_FOUND
}
